              - name: Checkout
                uses: actions/checkout@v4.1.7
            
              - name: Upload GitHub Pages artifact
                uses: actions/upload-pages-artifact@v3.0.1
            
              - name: Deploy GitHub Pages site
                uses: actions/deploy-pages@v4.0.5
            
